FROM node:22-alpine

WORKDIR /app

ENV NODE_ENV=production

RUN npm install -g pnpm@9.15.9

COPY pnpm-workspace.yaml pnpm-lock.yaml package.json ./
RUN pnpm install --frozen-lockfile --prod --prefer-offline

COPY tsconfig.json ./
COPY worker.ts ./
COPY src ./src

CMD ["pnpm", "worker"]
